// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Notify(arg1:string,arg2:string):Promise<void>;

export function OpenExternal(arg1:string):Promise<void>;

export function PendingOAuthURL():Promise<string>;

export function SaveFile(arg1:string,arg2:string):Promise<string>;
