// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Notify(arg1, arg2) {
  return window['go']['main']['DesktopApp']['Notify'](arg1, arg2);
}

export function OpenExternal(arg1) {
  return window['go']['main']['DesktopApp']['OpenExternal'](arg1);
}

export function PendingOAuthURL() {
  return window['go']['main']['DesktopApp']['PendingOAuthURL']();
}

export function SaveFile(arg1, arg2) {
  return window['go']['main']['DesktopApp']['SaveFile'](arg1, arg2);
}
