//go:build js

package webapp

import "syscall/js"

var budgetSignatureCallbacks []js.Func

// prepareBudgetSignatureCanvas binds one pointer-aware canvas while the
// approval dialog is visible. Signature pixels remain generated by the browser
// canvas; business validation and persistence stay in Go.
func prepareBudgetSignatureCanvas() bool {
	document := js.Global().Get("document")
	if document.IsUndefined() || document.IsNull() {
		return false
	}
	canvas := document.Call("getElementById", "budget-signature-canvas")
	if canvas.IsUndefined() || canvas.IsNull() {
		return false
	}
	if canvas.Get("__inovarBound").Type() == js.TypeBoolean && canvas.Get("__inovarBound").Bool() {
		return true
	}
	context := canvas.Call("getContext", "2d")
	if context.IsUndefined() || context.IsNull() {
		return false
	}
	context.Set("lineWidth", 2.5)
	context.Set("lineCap", "round")
	context.Set("lineJoin", "round")
	context.Set("strokeStyle", "#0f172a")
	canvas.Get("style").Set("touchAction", "none")

	var down js.Func
	down = js.FuncOf(func(this js.Value, args []js.Value) any {
		if len(args) == 0 {
			return nil
		}
		event := args[0]
		event.Call("preventDefault")
		rect := canvas.Call("getBoundingClientRect")
		x := (event.Get("clientX").Float() - rect.Get("left").Float()) * float64(canvas.Get("width").Int()) / rect.Get("width").Float()
		y := (event.Get("clientY").Float() - rect.Get("top").Float()) * float64(canvas.Get("height").Int()) / rect.Get("height").Float()
		context.Call("beginPath")
		context.Call("moveTo", x, y)
		canvas.Set("__inovarDrawing", true)
		canvas.Set("__inovarHasInk", true)
		if event.Get("pointerId").Type() == js.TypeNumber {
			canvas.Call("setPointerCapture", event.Get("pointerId"))
		}
		return nil
	})
	var move js.Func
	move = js.FuncOf(func(this js.Value, args []js.Value) any {
		if len(args) == 0 || canvas.Get("__inovarDrawing").Type() != js.TypeBoolean || !canvas.Get("__inovarDrawing").Bool() {
			return nil
		}
		event := args[0]
		event.Call("preventDefault")
		rect := canvas.Call("getBoundingClientRect")
		x := (event.Get("clientX").Float() - rect.Get("left").Float()) * float64(canvas.Get("width").Int()) / rect.Get("width").Float()
		y := (event.Get("clientY").Float() - rect.Get("top").Float()) * float64(canvas.Get("height").Int()) / rect.Get("height").Float()
		context.Call("lineTo", x, y)
		context.Call("stroke")
		return nil
	})
	var up js.Func
	up = js.FuncOf(func(this js.Value, args []js.Value) any {
		if canvas.Get("__inovarDrawing").Type() == js.TypeBoolean && canvas.Get("__inovarDrawing").Bool() {
			canvas.Set("__inovarDrawing", false)
			if canvas.Get("__inovarHasInk").Bool() {
				js.Global().Set("__inovarBudgetSignature", canvas.Call("toDataURL", "image/png").String())
			}
		}
		return nil
	})
	canvas.Call("addEventListener", "pointerdown", down)
	canvas.Call("addEventListener", "pointermove", move)
	canvas.Call("addEventListener", "pointerup", up)
	canvas.Call("addEventListener", "pointercancel", up)
	canvas.Set("__inovarPointerDown", down.Value)
	canvas.Set("__inovarPointerMove", move.Value)
	canvas.Set("__inovarPointerUp", up.Value)
	budgetSignatureCallbacks = append(budgetSignatureCallbacks, down, move, up)
	canvas.Set("__inovarBound", true)
	return true
}

func currentBudgetSignature() string {
	value := js.Global().Get("__inovarBudgetSignature")
	if value.IsUndefined() || value.IsNull() {
		return ""
	}
	return value.String()
}

func clearBudgetSignatureCanvas() {
	js.Global().Set("__inovarBudgetSignature", "")
	document := js.Global().Get("document")
	if document.IsUndefined() || document.IsNull() {
		return
	}
	canvas := document.Call("getElementById", "budget-signature-canvas")
	if canvas.IsUndefined() || canvas.IsNull() {
		return
	}
	if canvas.Get("__inovarBound").Type() == js.TypeBoolean && canvas.Get("__inovarBound").Bool() {
		canvas.Call("removeEventListener", "pointerdown", canvas.Get("__inovarPointerDown"))
		canvas.Call("removeEventListener", "pointermove", canvas.Get("__inovarPointerMove"))
		canvas.Call("removeEventListener", "pointerup", canvas.Get("__inovarPointerUp"))
		canvas.Call("removeEventListener", "pointercancel", canvas.Get("__inovarPointerUp"))
		for _, callback := range budgetSignatureCallbacks {
			callback.Release()
		}
		budgetSignatureCallbacks = nil
		canvas.Set("__inovarBound", false)
	}
	context := canvas.Call("getContext", "2d")
	context.Call("clearRect", 0, 0, canvas.Get("width").Int(), canvas.Get("height").Int())
	canvas.Set("__inovarHasInk", false)
	js.Global().Set("__inovarBudgetSignature", "")
}
