-- Private Postgres storage for the WhatsApp Go service and its whatsmeow device keys.
-- This schema is deliberately outside Supabase's default exposed `public` schema.
CREATE SCHEMA IF NOT EXISTS whatsapp;
REVOKE ALL ON SCHEMA whatsapp FROM PUBLIC, anon, authenticated, service_role;

ALTER DEFAULT PRIVILEGES IN SCHEMA whatsapp
  REVOKE ALL ON TABLES FROM PUBLIC, anon, authenticated, service_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA whatsapp
  REVOKE ALL ON SEQUENCES FROM PUBLIC, anon, authenticated, service_role;

CREATE TABLE IF NOT EXISTS whatsapp.api_sessions (
  id TEXT PRIMARY KEY,
  device_id TEXT NOT NULL UNIQUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS whatsapp.webhook_events (
  id TEXT PRIMARY KEY,
  payload BYTEA NOT NULL,
  attempts INTEGER NOT NULL DEFAULT 0,
  available_at BIGINT NOT NULL DEFAULT 0,
  created_at BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS whatsapp.api_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id TEXT NOT NULL,
  chat_jid TEXT NOT NULL,
  message_id TEXT NOT NULL,
  sender TEXT NOT NULL DEFAULT '',
  from_me BOOLEAN NOT NULL DEFAULT false,
  text TEXT NOT NULL DEFAULT '',
  media_type TEXT NOT NULL DEFAULT '',
  timestamp BIGINT NOT NULL,
  UNIQUE(session_id, chat_jid, message_id)
);
CREATE INDEX IF NOT EXISTS idx_api_messages_chat
  ON whatsapp.api_messages(session_id, chat_jid, timestamp);

CREATE TABLE IF NOT EXISTS whatsapp.api_products (
  id TEXT PRIMARY KEY,
  session_id TEXT NOT NULL,
  sku TEXT NOT NULL DEFAULT '',
  name TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  price TEXT NOT NULL DEFAULT '',
  currency TEXT NOT NULL DEFAULT 'BRL',
  image_url TEXT NOT NULL DEFAULT '',
  created_at BIGINT NOT NULL,
  updated_at BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS whatsapp.app_settings (
  key TEXT PRIMARY KEY,
  value TEXT NOT NULL
);

ALTER TABLE whatsapp.api_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE whatsapp.webhook_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE whatsapp.api_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE whatsapp.api_products ENABLE ROW LEVEL SECURITY;
ALTER TABLE whatsapp.app_settings ENABLE ROW LEVEL SECURITY;

COMMENT ON SCHEMA whatsapp IS 'Private WhatsApp Go service storage; not exposed through the Supabase Data API.';
